### ISSUE TITLE
Cookie 관련 에러

### ISSUE THREAD

**Issue by LaonCoder** [meety-service/meety-frontend#35]
- 헤더에 쿠키 담아 보낼 때 'Refused to set unsafe header "Cookie' 메시지 출력
- 쿠키 삭제 후 '/login/refresh' API 호출 시 서버 쪽 로그에 'cookie error g_state={"i_l":0}' 출력
@ch4n33

**Comment by ch4n33** [comment]
1.브라우저에서 explicit하게 쿠키를 헤더에 담을 경우 발생하는 문제입니다. 지금도 정상 동작하고 쿠키를 담는 코드를 지워도 동작할 것 같은데 잘 모르겠네요

2. 정상 동작입니다. 요청 헤더의 쿠키 부분에 로그인용 쿠키가 들어있지 않을 경우를 확인하는 테스트를 위해 찍은 로그입니다.
