### ISSUE TITLE
시간대 목록 정렬

### ISSUE THREAD

**Issue by enihsgnir** [meety-service/meety-frontend#40]
- 미팅 폼 작성 완료 페이지, 투표 폼 생성 페이지 등에서 시간대 목록을 정렬하여 표시하는 기준 및 방법 구현 필요

**Comment by LaonCoder** [comment]
구현 완료 했습니다! @enihsgnir 

- utils/meetingSort.js 파일 안에 **getSortedMeetingInfo()** 함수로 만들어 놓았습니다.
